scripts:
  - name: Install dependencies
    script: |
      pip install pyyaml
  - name: Build iOS Framework
    script: |
      chmod +x gradlew
      ./gradlew :composeApp:assembleIosArm64DebugFramework
  - name: Xcode build
    script: |
      xcode-project build-ipa \
        --project "$XCODE_PROJECT" \
        --scheme "$XCODE_SCHEME"
